#ifndef __BUILDNUMBER_H__
#define __BUILDNUMBER_H__

/**
 *This file is autogenerated by the wrc build number generator.
 *	(c) 2002 Western Reserve Controls Inc.
 *
 *  __BUILDNUMBER__ is a 32 bit integer linux epoch value generated in the makefile
 *  __BUILDNUMBER_VERSION__ is defined as 2
 *
 *  previous build number was incremented by an external program every build.
 *  This version uses the Linux epoch in the makefile (date +%s) command
 *
 *  changed buildnumber version to 2 to signify this change.
 *
 *
 **/

#define __BUILDNUMBER_VERSION__ 2

#ifndef __BUILDNUMBER__
#error "Build Number Not Defined. Check makefile flags"
//#define __BUILDNUMBER__			462
#endif // ifndef __BUILDNUMBER__

#endif
