#ifndef INCLUDE_GAURD_EE_ADDR
#define INCLUDE_GAURD_EE_ADDR
#include "dn_eeprm.h"
#define EE_HEAP_START EE_END_COMMON_AREA + 1
//---------->  EEaddr for JDC Revision 6

#define EE_SERIAL_CHARACTER_FORMAT EE_HEAP_START + 0
#define EE_SERIAL_BAUDRATE		   EE_HEAP_START + 1
#define EE_MAX_NUMBER_RCV_CHARS	   EE_HEAP_START + 2
#define EE_RCV_DATA_STR_TYPE	   EE_HEAP_START + 3
#define EE_RCV_DELIM_START_MODE	   EE_HEAP_START + 4
#define EE_RCV_DELIM_END_MODE	   EE_HEAP_START + 5
#define EE_RCV_DELIM_START_CHAR	   EE_HEAP_START + 6
#define EE_RCV_DELIM_END_CHAR	   EE_HEAP_START + 7
#define EE_PAD_MODE				   EE_HEAP_START + 8
#define EE_PAD_CHAR				   EE_HEAP_START + 9
#define EE_RCV_SWAP_MODE		   EE_HEAP_START + 10
#define EE_RCV_REC_AUTO_INC		   EE_HEAP_START + 11
#define EE_MAX_NUMBER_TX_CHARS	   EE_HEAP_START + 12
#define EE_TX_DATA_STR_TYPE		   EE_HEAP_START + 13
#define EE_TX_END_DELIM			   EE_HEAP_START + 14
#define EE_TX_END_DELIM_MODE	   EE_HEAP_START + 15
#define EE_TX_SWAP_MODE			   EE_HEAP_START + 16
#define EE_TX_REC_HEADER_MODE	   EE_HEAP_START + 17
#define EE_CUST_PARAM_INIT_VAR	   EE_HEAP_START + 18

//TODO verify with memory address
#define EE_RECBUFFER_ADDR 		   			EE_HEAP_START + 19
#define EE_MODBUSMODE_ADDR         			EE_HEAP_START + 20
#define EE_XMITBUFFER_ADDR		   			EE_HEAP_START + 21
#define MB_TYPE_NVRAM_ADDR		   			EE_HEAP_START + 22
#define MB_TIMEOUT_NVRAM_ADDR				EE_HEAP_START + 23
#define MB_SLAVEID_NVRAM_ADDR				EE_HEAP_START + 24
#define MB_COILSTART_NVRAM_ADDR				EE_HEAP_START + 25
#define MB_COILCOUNT_NVRAM_ADDR				EE_HEAP_START + 26
#define MB_DISCINPUTSTART_NVRAM_ADDR		EE_HEAP_START + 27
#define MB_DISCINPUTCOUNT_NVRAM_ADDR		EE_HEAP_START + 28
#define MB_INREGSTART_NVRAM_ADDR			EE_HEAP_START + 29
#define MB_INREGCOUNT_NVRAM_ADDR			EE_HEAP_START + 30
#define MB_HOLDREGSTART_NVRAM_ADDR			EE_HEAP_START + 31
#define MB_HOLDREGCOUNT_NVRAM_ADDR			EE_HEAP_START + 32

#endif
